# Generated by Django 4.1.5 on 2023-01-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO product_app_product(
                id,
                name,
                category_id
            )  
            SELECT 
                id, 
                name, 
                category_id
            FROM
                catalog_app_product;       
        """, reverse_sql="""
            INSERT INTO catalog_app_product (
                id,
                name,
                category_id
            )
            SELECT 
                id,
                name,
                category_id
            FROM
                product_app_product;
        """)
    ]
