# Generated by Django 4.1.5 on 2023-01-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
    
    # python manage.py sqlmigrate product_app 0002
    # BEGIN;
    # --
    # -- Alter field name on product
    # --
    # CREATE TABLE "new__product_app_product" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "category_id" bigint NOT NULL REFERENCES "catalog_app_category" ("id") DEFERRABLE INITIALLY DEFERRED);
    # INSERT INTO "new__product_app_product" ("id", "category_id", "name") SELECT "id", "category_id", "name" FROM "product_app_product";
    # DROP TABLE "product_app_product";
    # ALTER TABLE "new__product_app_product" RENAME TO "product_app_product";
    # CREATE INDEX "product_app_product_category_id_5de7b7e6" ON "product_app_product" ("category_id");
    # COMMIT;
