# Generated by Django 4.1.5 on 2023-01-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog_app.product')),
            ],
        ),
    ]
