# Generated by Django 4.1.5 on 2023-01-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='product',
                    name='category',
                ),
            ],
            database_operations=[],
        )
    ]
