# Generated by Django 4.1.5 on 2023-01-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_app', '0002_alter_sale_product'),
        ('catalog_app', '0002_remove_product_category'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Product',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Product',
                    table='product_app_product',
                ),
            ],
        )
    ]
